"""empty message

Revision ID: 2aa5158be6b3
Revises: 523e1c6c7be1
Create Date: 2017-06-25 12:34:59.276995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa5158be6b3'
down_revision = '523e1c6c7be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainee', sa.Column('session_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trainee', 'session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trainee', type_='foreignkey')
    op.drop_column('trainee', 'session_id')
    # ### end Alembic commands ###
