"""empty message

Revision ID: fe0e5b464ac2
Revises: 
Create Date: 2017-06-24 23:26:19.656023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe0e5b464ac2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trainee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('trainer_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainee_email'), 'trainee', ['email'], unique=True)
    op.create_index(op.f('ix_trainee_first_name'), 'trainee', ['first_name'], unique=False)
    op.create_index(op.f('ix_trainee_last_name'), 'trainee', ['last_name'], unique=False)
    op.create_index(op.f('ix_trainee_username'), 'trainee', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainee_username'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_last_name'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_first_name'), table_name='trainee')
    op.drop_index(op.f('ix_trainee_email'), table_name='trainee')
    op.drop_table('trainee')
    op.drop_table('trainer')
    # ### end Alembic commands ###
